import type { Opportunity, Portal } from "./types";

const now = new Date();
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "demo-1",
    external_id: "demo-cybersec-001",
    portal: "sam_gov",
    title: "Cybersecurity Operations Support Services",
    agency: "Department of Defense",
    naics_codes: ["541512"],
    set_asides: ["8a"],
    value_display: "$2.5M",
    value_min: 2500000,
    value_max: null,
    state: "VA",
    response_deadline: daysFromNow(1),
    posted_date: daysAgo(5),
    description: "DoD seeks cybersecurity operations support for 24/7 monitoring and incident response across enterprise systems.",
    opportunity_url: "https://sam.gov/opp/demo-001",
    solicitation_number: "W52P1J-26-R-0001",
    relevance_score: 0.92,
    relevance_label: "High",
    relevance_reasons: ["NAICS 541512 matches profile", "8(a) set-aside matches certification", "Value range within profile"],
    days_until_deadline: 1,
    urgency_tier: "urgent",
    is_urgent: true,
    scan_id: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
  },
  {
    id: "demo-2",
    external_id: "demo-itmod-002",
    portal: "sam_gov",
    title: "IT Modernization & Cloud Migration Program",
    agency: "General Services Administration",
    naics_codes: ["541511"],
    set_asides: ["sba"],
    value_display: "$5M–$10M",
    value_min: 5000000,
    value_max: 10000000,
    state: "DC",
    response_deadline: daysFromNow(2),
    posted_date: daysAgo(3),
    description: "GSA seeks contractor to modernize legacy IT systems and migrate critical workloads to cloud infrastructure.",
    opportunity_url: "https://sam.gov/opp/demo-002",
    solicitation_number: "47QRAA26R0002",
    relevance_score: 0.88,
    relevance_label: "High",
    relevance_reasons: ["NAICS 541511 matches profile", "Value range in profile range"],
    days_until_deadline: 2,
    urgency_tier: "urgent",
    is_urgent: true,
    scan_id: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: "demo-3",
    external_id: "demo-zerotrust-003",
    portal: "cal_eprocure",
    title: "Zero Trust Architecture Implementation",
    agency: "Department of Homeland Security",
    naics_codes: ["541512"],
    set_asides: ["sdvosb"],
    value_display: "$1.2M",
    value_min: 1200000,
    value_max: null,
    state: "MD",
    response_deadline: daysFromNow(5),
    posted_date: daysAgo(2),
    description: "DHS requires zero trust architecture design and implementation across enterprise network infrastructure.",
    opportunity_url: "https://caleprocure.ca.gov/opp/demo-003",
    solicitation_number: "70RDSD26R0003",
    relevance_score: 0.85,
    relevance_label: "High",
    relevance_reasons: ["NAICS 541512 matches profile", "SDVOSB set-aside matches certification"],
    days_until_deadline: 5,
    urgency_tier: "closing_soon",
    is_urgent: false,
    scan_id: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: "demo-4",
    external_id: "demo-netsec-004",
    portal: "tx_smartbuy",
    title: "Enterprise Network Security Assessment & Penetration Testing",
    agency: "Department of Defense",
    naics_codes: ["541512"],
    set_asides: [],
    value_display: "$800K",
    value_min: 800000,
    value_max: null,
    state: "TX",
    response_deadline: daysFromNow(10),
    posted_date: daysAgo(1),
    description: "DoD requires comprehensive enterprise network security assessment and vulnerability analysis.",
    opportunity_url: "https://txsmartbuy.com/opp/demo-004",
    solicitation_number: "W911NF26R0004",
    relevance_score: 0.87,
    relevance_label: "High",
    relevance_reasons: ["NAICS 541512 matches profile", "State TX matches profile"],
    days_until_deadline: 10,
    urgency_tier: "normal",
    is_urgent: false,
    scan_id: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "demo-5",
    external_id: "demo-swdev-005",
    portal: "sam_gov",
    title: "Software Development Services — DISA Enterprise Apps",
    agency: "DISA",
    naics_codes: ["541511"],
    set_asides: [],
    value_display: "$500K",
    value_min: 500000,
    value_max: null,
    state: "MD",
    response_deadline: daysFromNow(14),
    posted_date: daysAgo(7),
    description: "DISA seeks software development services for enterprise application modernization and legacy system replacement.",
    opportunity_url: "https://sam.gov/opp/demo-005",
    solicitation_number: "HC102826R0005",
    relevance_score: 0.55,
    relevance_label: "Medium",
    relevance_reasons: ["NAICS 541511 matches profile"],
    days_until_deadline: 14,
    urgency_tier: "normal",
    is_urgent: false,
    scan_id: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(2),
  },
];

export const MOCK_PORTALS: Portal[] = [
  {
    id: "sam_gov",
    name: "sam_gov",
    display_name: "SAM.gov",
    base_url: "https://sam.gov",
    status: "healthy",
    last_scan_at: daysAgo(0.1),
    opportunities_count: 312,
  },
  {
    id: "cal_eprocure",
    name: "cal_eprocure",
    display_name: "Cal eProcure",
    base_url: "https://caleprocure.ca.gov",
    status: "healthy",
    last_scan_at: daysAgo(0.3),
    opportunities_count: 87,
  },
  {
    id: "tx_smartbuy",
    name: "tx_smartbuy",
    display_name: "Texas SmartBuy",
    base_url: "https://txsmartbuy.com",
    status: "degraded",
    last_scan_at: daysAgo(2),
    opportunities_count: 45,
  },
];
